import type { Locale } from "@/i18n/locale";

const hu = {
  brand: "Szcenárió · számla",
  payTitle: "Fizetés",
  thanksTitle: "Köszönjük",
  thanksBody: "Ha a fizetés sikeres, a számla a megadott e-mailre megy.",
  order: "Rendelés",
  transferTitle: "Belföldi átutalás",
  transferLead: "A díjbekérőhöz ezeket add meg a bankodban. A jóváírás után a végszámla automatikusan megy.",
  proforma: "Díjbekérő",
  proformaMail: "— a Számlázz.hu a megadott e-mailre is elküldi.",
  stepAmount: "1. Összeg (bruttó fizetendő)",
  stepPayee: "2. Kedvezményezett",
  stepIban: "3. Számlaszám / IBAN",
  stepMemo: "4. Közlemény — ezt írd be pontosan",
  stepMemoHint: "Ebből párosítjuk a befizetést. Más szöveget ne tegyél mellé.",
  campus: "campus",
  cardNote: "A kártyaadat a Stripe / Barion hosted oldalán marad.",
  yearlySub: "Éves előfizetés",
  monthlySub: "Havi előfizetés",
  gross: "bruttó",
  net: "nettó",
  vatShort: "ÁFA",
  perYear: "/ év",
  perMonth: "/ hó",
  savePctYearly: "−{n}% megtakarítás az éves díjjal",
  name: "Cégnév / név",
  email: "E-mail",
  country: "Megrendelő országa",
  address: "Számlázási cím",
  taxId: "Adószám",
  taxPh: "12345678-2-41 vagy DE123456789",
  lookup: "Cégadatok NAV / VIES alapján",
  lookupBusy: "Lekérdezés…",
  lookupEmpty: "Nincs találat.",
  lookupVies: "VIES kitöltötte a cégadatokat.",
  lookupNav: "NAV-proxy kitöltötte a cégadatokat.",
  lookupOffline: "A lekérdezés most nem elérhető.",
  payMethod: "Fizetési mód",
  transfer: "Belföldi átutalás — díjbekérő, egyedi közlemény",
  stripe: "Stripe — kártya, Apple Pay, Google Pay",
  barion: "Barion — kártya, Apple Pay, Google Pay",
  noKey: "(kulcs nincs beállítva)",
  submit: "Tovább · {n}",
  busy: "Feldolgozás…",
  errOrder: "A rendelést nem sikerült rögzíteni.",
  errNet: "Hálózati hiba.",
  starter: "Alapcsomag",
  pro: "Üzleti / Pro",
  expert: "Nagyvállalati / Enterprise",
  campusTier: "Hallgatói / Campus",
};

const en: typeof hu = {
  brand: "Szcenárió · invoice",
  payTitle: "Payment",
  thanksTitle: "Thank you",
  thanksBody: "If payment succeeds, the invoice goes to the e-mail you gave.",
  order: "Order",
  transferTitle: "Domestic transfer",
  transferLead: "Use these details in your bank for the proforma. After credit, the final invoice is sent automatically.",
  proforma: "Proforma",
  proformaMail: "— Számlázz.hu also sends it to the given e-mail.",
  stepAmount: "1. Amount (gross due)",
  stepPayee: "2. Payee",
  stepIban: "3. Account / IBAN",
  stepMemo: "4. Payment reference — enter this exactly",
  stepMemoHint: "We match the payment from this. Do not add other text.",
  campus: "campus",
  cardNote: "Card data stays on the Stripe / Barion hosted page.",
  yearlySub: "Yearly subscription",
  monthlySub: "Monthly subscription",
  gross: "gross",
  net: "net",
  vatShort: "VAT",
  perYear: "/ yr",
  perMonth: "/ mo",
  savePctYearly: "−{n}% savings with yearly billing",
  name: "Company / name",
  email: "E-mail",
  country: "Buyer country",
  address: "Billing address",
  taxId: "Tax ID",
  taxPh: "12345678-2-41 or DE123456789",
  lookup: "Fill from NAV / VIES",
  lookupBusy: "Looking up…",
  lookupEmpty: "No match.",
  lookupVies: "VIES filled the company data.",
  lookupNav: "NAV proxy filled the company data.",
  lookupOffline: "Lookup is not available now.",
  payMethod: "Payment method",
  transfer: "Domestic transfer — proforma, unique reference",
  stripe: "Stripe — card, Apple Pay, Google Pay",
  barion: "Barion — card, Apple Pay, Google Pay",
  noKey: "(key not set)",
  submit: "Continue · {n}",
  busy: "Processing…",
  errOrder: "The order could not be saved.",
  errNet: "Network error.",
  starter: "Starter",
  pro: "Business / Pro",
  expert: "Enterprise",
  campusTier: "Student / Campus",
};

export function billCopy(locale: Locale) {
  return locale === "en" ? en : hu;
}

export function tierLabel(locale: Locale, tier: string) {
  const c = billCopy(locale);
  if (tier === "starter") return c.starter;
  if (tier === "pro") return c.pro;
  if (tier === "expert") return c.expert;
  if (tier === "campus") return c.campusTier;
  return tier;
}
