import type { Locale } from "@/i18n/locale";

const hu = {
  brand: "Szcenárió · számlázás",
  homeTitle: "Számlázás",
  homeLead:
    "Meglévő rendeléshez add meg a rendelési azonosítót (vagy SZC-kódot) és a megrendelő e-mailt. Új csomaghoz a főoldal árlistája vezet ide.",
  homePricingCta: "Csomagok a főoldalon",
  homePickLead: "Vagy válassz csomagot itt — a számlázási űrlap a kiválasztott tervvel nyílik.",
  homePickStarter: "Basic",
  homePickPro: "Pro Szcenárió",
  homePickExpert: "Enterprise & Csapatok",
  loginTitle: "Rendelés megnyitása",
  loginToken: "Rendelésazonosító vagy SZC-kód",
  loginTokenPh: "pl. SZC-… vagy rendelés-UUID",
  loginEmail: "Megrendelő e-mail",
  loginSubmit: "Megnyitás",
  loginBusy: "Ellenőrzés…",
  loginHint: "Mindkét adat kell — így nem nyílik meg idegen rendelés.",
  loginErr: "Nem egyezik, vagy a rendelés nem található.",
  loginNeed: "Azonosító és érvényes e-mail kell.",
  logout: "Kilépés",
  portalTitle: "Rendelésed",
  portalStatus: "Státusz",
  portalTier: "Csomag",
  portalAmount: "Összeg",
  portalProforma: "Díjbekérő",
  portalInvoice: "Számla",
  portalCode: "Közlemény / token",
  statusPending: "Függőben",
  statusAwaiting: "Átutalásra vár",
  statusPaid: "Fizetve",
  statusInvoiced: "Számlázva",
  statusFailed: "Sikertelen",
  payTitle: "Fizetés",
  thanksTitle: "Köszönjük",
  thanksBody: "Ha a fizetés sikeres, a számla a megadott e-mailre megy.",
  order: "Rendelés",
  transferTitle: "Belföldi átutalás",
  transferLead: "A díjbekérőhöz ezeket add meg a bankodban. A jóváírás után a végszámla automatikusan megy.",
  proforma: "Díjbekérő",
  proformaMail: "— a Számlázz.hu a megadott e-mailre is elküldi.",
  proformaReady: "A díjbekérő elkészült.",
  openBuyerAccount: "Megnyitás a Számlázz.hu vevői fiókban",
  stepAmount: "1. Összeg (bruttó fizetendő)",
  stepPayee: "2. Kedvezményezett",
  stepIban: "3. Számlaszám / IBAN",
  stepMemo: "4. Közlemény — ezt írd be pontosan",
  stepMemoHint: "Ebből párosítjuk a befizetést. Más szöveget ne tegyél mellé.",
  campus: "campus",
  cardNote: "Két fizetési mód: banki átutalás, vagy online kártyás fizetés a Számlázz.hu → Barion oldalon. A kártyaadat ott marad.",
  yearlySub: "örökös licenc · 1. év",
  monthlySub: "havi campus díj",
  gross: "bruttó",
  net: "nettó",
  vatShort: "ÁFA",
  perYear: "/ év",
  perMonth: "/ hó",
  savePctYearly: "−{n}% megtakarítás az éves díjjal",
  cycleYearly: "Éves számlázás (−{n}%)",
  cycleMonthly: "Havi számlázás",
  nextRenewal: "Következő fordulónap: {date}",
  name: "Cégnév / név",
  email: "E-mail",
  country: "Megrendelő országa",
  address: "Számlázási cím",
  taxId: "Adószám",
  taxIdRequired: "Adószám (kötelező céges vásárláskor)",
  taxPh: "12345678-2-41 vagy DE123456789",
  buyerKindTitle: "Vásárló típusa",
  buyerB2c: "Magánszemélyként vásárolok (B2C)",
  buyerB2cHint: "Szakmámon kívül — fogyasztói szabályok.",
  buyerB2b: "Cégként / vállalkozóként vásárolok (B2B)",
  buyerB2bHint: "Adószám kötelező — fogyasztói elállás nem jár.",
  b2cImmediateConsent:
    "Kifejezetten kérem a digitális szolgáltatás azonnali megkezdését, és tudomásul veszem, hogy ezzel a 14 napos elállási jogomat elveszítem (45/2014. Korm. r. 29. § (1) m).",
  b2bNoWithdrawal: "Céges vásárlás esetén a fogyasztói 14 napos elállási jog nem alkalmazandó.",
  acceptAszf: "Elfogadom az ÁSZF-et és az adatvédelmi tájékoztatót.",
  needBuyerConsent: "A kötelező nyilatkozatok elfogadása szükséges.",
  needTaxIdB2b: "Céges vásárláskor az adószám megadása kötelező.",
  lookup: "Cégadatok NAV / VIES alapján",
  lookupBusy: "Lekérdezés…",
  lookupEmpty: "Nincs találat.",
  lookupVies: "VIES kitöltötte a cégadatokat.",
  lookupNav: "NAV-proxy kitöltötte a cégadatokat.",
  lookupOffline: "A lekérdezés most nem elérhető.",
  payMethod: "Fizetési mód",
  transfer: "Banki átutalás",
  transferHint: "Díjbekérő, egyedi közlemény",
  stripe: "Stripe — kártya, Apple Pay, Google Pay",
  barion: "Online kártyás fizetés",
  barionHint: "Számlázz.hu → Barion (Visa, Mastercard, Apple Pay, Google Pay)",
  noKey: "(kulcs nincs beállítva)",
  payLogosAlt: "Barion — elfogadott fizetési módok",
  needCheckout: "A megrendeléshez töltsd ki a kötelező számlázási adatokat.",
  liveKeysMissing: "Éles számlázási kulcsok hiányoznak: {keys}",
  submit: "Megrendelés véglegesítése · {n}",
  busy: "Feldolgozás…",
  sandboxNote: "Teszt mód — a díjbekérő a Számlázz.hu sandbox / teszt fiókba megy (vagy helyi mock).",
  pdfDownload: "Díjbekérő PDF letöltése",
  errOrder: "A rendelést nem sikerült rögzíteni.",
  errNet: "Hálózati hiba.",
  starter: "Basic",
  pro: "Pro Szcenárió",
  expert: "Enterprise & Csapatok",
  campusTier: "Campus",
  enterpriseBadge: "Későbbi időpontban érhető el",
  enterpriseCta: "Kapcsolatfelvétel / Ajánlatkérés",
  enterpriseInquiryLead:
    "Az Enterprise csomag előjegyzésre érhető el. Az ár és a kapacitás (Aktív Case / Aktív Slot) tájékoztató értékhorgony. Nincs önkiszolgáló checkout.",
};

const en: typeof hu = {
  brand: "Szcenárió · billing",
  homeTitle: "Billing",
  homeLead:
    "For an existing order enter the order id (or SZC code) and the buyer e-mail. New packages start from the main pricing list.",
  homePricingCta: "Packages on the main site",
  homePickLead: "Or pick a plan here — checkout opens with that package.",
  homePickStarter: "Basic",
  homePickPro: "Pro Szcenárió",
  homePickExpert: "Enterprise & Csapatok",
  loginTitle: "Open order",
  loginToken: "Order id or SZC code",
  loginTokenPh: "e.g. SZC-… or order UUID",
  loginEmail: "Buyer e-mail",
  loginSubmit: "Open",
  loginBusy: "Checking…",
  loginHint: "Both fields are required — so someone else’s order cannot open.",
  loginErr: "No match, or the order was not found.",
  loginNeed: "Token and a valid e-mail are required.",
  logout: "Sign out",
  portalTitle: "Your order",
  portalStatus: "Status",
  portalTier: "Plan",
  portalAmount: "Amount",
  portalProforma: "Proforma",
  portalInvoice: "Invoice",
  portalCode: "Reference / token",
  statusPending: "Pending",
  statusAwaiting: "Awaiting transfer",
  statusPaid: "Paid",
  statusInvoiced: "Invoiced",
  statusFailed: "Failed",
  payTitle: "Payment",
  thanksTitle: "Thank you",
  thanksBody: "If payment succeeds, the invoice goes to the e-mail you gave.",
  order: "Order",
  transferTitle: "Domestic transfer",
  transferLead: "Use these details in your bank for the proforma. After credit, the final invoice is sent automatically.",
  proforma: "Proforma",
  proformaMail: "— Számlázz.hu also sends it to the given e-mail.",
  proformaReady: "The proforma is ready.",
  openBuyerAccount: "Open in the Számlázz.hu customer account",
  stepAmount: "1. Amount (gross due)",
  stepPayee: "2. Payee",
  stepIban: "3. Account / IBAN",
  stepMemo: "4. Payment reference — enter this exactly",
  stepMemoHint: "We match the payment from this. Do not add other text.",
  campus: "campus",
  cardNote: "Two payment methods: bank transfer, or online card via Számlázz.hu → Barion. Card data stays there.",
  yearlySub: "perpetual license · year 1",
  monthlySub: "campus monthly token",
  gross: "gross",
  net: "net",
  vatShort: "VAT",
  perYear: "/ yr",
  perMonth: "/ mo",
  savePctYearly: "−{n}% savings with yearly billing",
  cycleYearly: "Yearly billing (−{n}%)",
  cycleMonthly: "Monthly billing",
  nextRenewal: "Next renewal: {date}",
  name: "Company / name",
  email: "E-mail",
  country: "Buyer country",
  address: "Billing address",
  taxId: "Tax ID",
  taxIdRequired: "Tax ID (required for business purchase)",
  taxPh: "12345678-2-41 or DE123456789",
  buyerKindTitle: "Buyer type",
  buyerB2c: "I buy as a private individual (B2C)",
  buyerB2cHint: "Outside my trade — consumer rules apply.",
  buyerB2b: "I buy as a company / sole trader (B2B)",
  buyerB2bHint: "Tax ID required — consumer withdrawal does not apply.",
  b2cImmediateConsent:
    "I expressly request immediate start of the digital service and acknowledge that I lose my 14-day withdrawal right (Gov. Decree 45/2014 §29(1)(m)).",
  b2bNoWithdrawal: "For business purchases the consumer 14-day withdrawal right does not apply.",
  acceptAszf: "I accept the Terms of Service and the privacy notice.",
  needBuyerConsent: "Required declarations must be accepted.",
  needTaxIdB2b: "A tax ID is required for business purchases.",
  lookup: "Fill from NAV / VIES",
  lookupBusy: "Looking up…",
  lookupEmpty: "No match.",
  lookupVies: "VIES filled the company data.",
  lookupNav: "NAV proxy filled the company data.",
  lookupOffline: "Lookup is not available now.",
  payMethod: "Payment method",
  transfer: "Bank transfer",
  transferHint: "Proforma, unique reference",
  stripe: "Stripe — card, Apple Pay, Google Pay",
  barion: "Online card payment",
  barionHint: "Számlázz.hu → Barion (Visa, Mastercard, Apple Pay, Google Pay)",
  noKey: "(key not set)",
  payLogosAlt: "Barion — accepted payment methods",
  needCheckout: "Fill in every required billing field before placing the order.",
  liveKeysMissing: "Live billing keys are missing: {keys}",
  submit: "Place order · {n}",
  busy: "Processing…",
  sandboxNote: "Test mode — the proforma goes to the Számlázz.hu sandbox / test account (or a local mock).",
  pdfDownload: "Download proforma PDF",
  errOrder: "The order could not be saved.",
  errNet: "Network error.",
  starter: "Basic",
  pro: "Pro Szcenárió",
  expert: "Enterprise & Csapatok",
  campusTier: "Campus",
  enterpriseBadge: "Available at a later date",
  enterpriseCta: "Contact / request a quote",
  enterpriseInquiryLead:
    "The Enterprise plan is available on waitlist. Price and capacity (Active Case / Active Slot) stay visible as a value anchor. There is no self-serve checkout.",
};

export function billCopy(locale: Locale) {
  return locale === "en" ? en : hu;
}

export function tierLabel(locale: Locale, tier: string) {
  const c = billCopy(locale);
  if (tier === "starter") return c.starter;
  if (tier === "pro") return c.pro;
  if (tier === "expert") return c.expert;
  if (tier === "campus") return c.campusTier;
  return tier;
}

export function statusLabel(locale: Locale, status: string) {
  const c = billCopy(locale);
  if (status === "pending") return c.statusPending;
  if (status === "awaiting_transfer") return c.statusAwaiting;
  if (status === "paid") return c.statusPaid;
  if (status === "invoiced") return c.statusInvoiced;
  if (status === "failed") return c.statusFailed;
  return status;
}
