/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AszfRouteImport } from './routes/aszf'
import { Route as BcpRouteImport } from './routes/bcp'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as KotelRouteImport } from './routes/kotel'
import { Route as KozossegRouteImport } from './routes/kozosseg'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MakroRouteImport } from './routes/makro'
import { Route as OktatasRouteImport } from './routes/oktatas'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StrategiaRouteImport } from './routes/strategia'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as LoginActivateRouteImport } from './routes/login_.activate'
import { Route as FOktatasSzimulacioIndexRouteImport } from './routes/f/oktatas-szimulacio/index'
import { Route as FOktatasSzimulacioCheckoutRouteImport } from './routes/f/oktatas-szimulacio/checkout'
import { Route as FOktatasSzimulacioDemoRouteImport } from './routes/f/oktatas-szimulacio/demo'
import { Route as FOktatasSzimulacioPricingRouteImport } from './routes/f/oktatas-szimulacio/pricing'
import { Route as FUzletiStrategiaIndexRouteImport } from './routes/f/uzleti-strategia/index'
import { Route as FUzletiStrategiaCheckoutRouteImport } from './routes/f/uzleti-strategia/checkout'
import { Route as FUzletiStrategiaDemoRouteImport } from './routes/f/uzleti-strategia/demo'
import { Route as FUzletiStrategiaPricingRouteImport } from './routes/f/uzleti-strategia/pricing'
import { Route as FValsagRezilienciaIndexRouteImport } from './routes/f/valsag-reziliencia/index'
import { Route as FValsagRezilienciaCheckoutRouteImport } from './routes/f/valsag-reziliencia/checkout'
import { Route as FValsagRezilienciaDemoRouteImport } from './routes/f/valsag-reziliencia/demo'
import { Route as FValsagRezilienciaPricingRouteImport } from './routes/f/valsag-reziliencia/pricing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AszfRoute = AszfRouteImport.update({
  id: '/aszf',
  path: '/aszf',
  getParentRoute: () => rootRouteImport,
} as any)
const BcpRoute = BcpRouteImport.update({
  id: '/bcp',
  path: '/bcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const KotelRoute = KotelRouteImport.update({
  id: '/kotel',
  path: '/kotel',
  getParentRoute: () => rootRouteImport,
} as any)
const KozossegRoute = KozossegRouteImport.update({
  id: '/kozosseg',
  path: '/kozosseg',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MakroRoute = MakroRouteImport.update({
  id: '/makro',
  path: '/makro',
  getParentRoute: () => rootRouteImport,
} as any)
const OktatasRoute = OktatasRouteImport.update({
  id: '/oktatas',
  path: '/oktatas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiaRoute = StrategiaRouteImport.update({
  id: '/strategia',
  path: '/strategia',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginActivateRoute = LoginActivateRouteImport.update({
  id: '/login_/activate',
  path: '/login/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const FOktatasSzimulacioIndexRoute = FOktatasSzimulacioIndexRouteImport.update({
  id: '/f/oktatas-szimulacio/',
  path: '/f/oktatas-szimulacio/',
  getParentRoute: () => rootRouteImport,
} as any)
const FOktatasSzimulacioCheckoutRoute =
  FOktatasSzimulacioCheckoutRouteImport.update({
    id: '/f/oktatas-szimulacio/checkout',
    path: '/f/oktatas-szimulacio/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const FOktatasSzimulacioDemoRoute = FOktatasSzimulacioDemoRouteImport.update({
  id: '/f/oktatas-szimulacio/demo',
  path: '/f/oktatas-szimulacio/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FOktatasSzimulacioPricingRoute =
  FOktatasSzimulacioPricingRouteImport.update({
    id: '/f/oktatas-szimulacio/pricing',
    path: '/f/oktatas-szimulacio/pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
const FUzletiStrategiaIndexRoute = FUzletiStrategiaIndexRouteImport.update({
  id: '/f/uzleti-strategia/',
  path: '/f/uzleti-strategia/',
  getParentRoute: () => rootRouteImport,
} as any)
const FUzletiStrategiaCheckoutRoute =
  FUzletiStrategiaCheckoutRouteImport.update({
    id: '/f/uzleti-strategia/checkout',
    path: '/f/uzleti-strategia/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const FUzletiStrategiaDemoRoute = FUzletiStrategiaDemoRouteImport.update({
  id: '/f/uzleti-strategia/demo',
  path: '/f/uzleti-strategia/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FUzletiStrategiaPricingRoute = FUzletiStrategiaPricingRouteImport.update({
  id: '/f/uzleti-strategia/pricing',
  path: '/f/uzleti-strategia/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FValsagRezilienciaIndexRoute = FValsagRezilienciaIndexRouteImport.update({
  id: '/f/valsag-reziliencia/',
  path: '/f/valsag-reziliencia/',
  getParentRoute: () => rootRouteImport,
} as any)
const FValsagRezilienciaCheckoutRoute =
  FValsagRezilienciaCheckoutRouteImport.update({
    id: '/f/valsag-reziliencia/checkout',
    path: '/f/valsag-reziliencia/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const FValsagRezilienciaDemoRoute = FValsagRezilienciaDemoRouteImport.update({
  id: '/f/valsag-reziliencia/demo',
  path: '/f/valsag-reziliencia/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FValsagRezilienciaPricingRoute =
  FValsagRezilienciaPricingRouteImport.update({
    id: '/f/valsag-reziliencia/pricing',
    path: '/f/valsag-reziliencia/pricing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/aszf': typeof AszfRoute
  '/bcp': typeof BcpRoute
  '/connect': typeof ConnectRoute
  '/devices': typeof DevicesRoute
  '/gdpr': typeof GdprRoute
  '/kotel': typeof KotelRoute
  '/kozosseg': typeof KozossegRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/makro': typeof MakroRoute
  '/oktatas': typeof OktatasRoute
  '/references': typeof ReferencesRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/strategia': typeof StrategiaRoute
  '/ticket': typeof TicketRoute
  '/login/activate': typeof LoginActivateRoute
  '/f/oktatas-szimulacio/checkout': typeof FOktatasSzimulacioCheckoutRoute
  '/f/oktatas-szimulacio/demo': typeof FOktatasSzimulacioDemoRoute
  '/f/oktatas-szimulacio/pricing': typeof FOktatasSzimulacioPricingRoute
  '/f/uzleti-strategia/checkout': typeof FUzletiStrategiaCheckoutRoute
  '/f/uzleti-strategia/demo': typeof FUzletiStrategiaDemoRoute
  '/f/uzleti-strategia/pricing': typeof FUzletiStrategiaPricingRoute
  '/f/valsag-reziliencia/checkout': typeof FValsagRezilienciaCheckoutRoute
  '/f/valsag-reziliencia/demo': typeof FValsagRezilienciaDemoRoute
  '/f/valsag-reziliencia/pricing': typeof FValsagRezilienciaPricingRoute
  '/f/oktatas-szimulacio/': typeof FOktatasSzimulacioIndexRoute
  '/f/uzleti-strategia/': typeof FUzletiStrategiaIndexRoute
  '/f/valsag-reziliencia/': typeof FValsagRezilienciaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/aszf': typeof AszfRoute
  '/bcp': typeof BcpRoute
  '/connect': typeof ConnectRoute
  '/devices': typeof DevicesRoute
  '/gdpr': typeof GdprRoute
  '/kotel': typeof KotelRoute
  '/kozosseg': typeof KozossegRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/makro': typeof MakroRoute
  '/oktatas': typeof OktatasRoute
  '/references': typeof ReferencesRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/strategia': typeof StrategiaRoute
  '/ticket': typeof TicketRoute
  '/login/activate': typeof LoginActivateRoute
  '/f/oktatas-szimulacio/checkout': typeof FOktatasSzimulacioCheckoutRoute
  '/f/oktatas-szimulacio/demo': typeof FOktatasSzimulacioDemoRoute
  '/f/oktatas-szimulacio/pricing': typeof FOktatasSzimulacioPricingRoute
  '/f/uzleti-strategia/checkout': typeof FUzletiStrategiaCheckoutRoute
  '/f/uzleti-strategia/demo': typeof FUzletiStrategiaDemoRoute
  '/f/uzleti-strategia/pricing': typeof FUzletiStrategiaPricingRoute
  '/f/valsag-reziliencia/checkout': typeof FValsagRezilienciaCheckoutRoute
  '/f/valsag-reziliencia/demo': typeof FValsagRezilienciaDemoRoute
  '/f/valsag-reziliencia/pricing': typeof FValsagRezilienciaPricingRoute
  '/f/oktatas-szimulacio': typeof FOktatasSzimulacioIndexRoute
  '/f/uzleti-strategia': typeof FUzletiStrategiaIndexRoute
  '/f/valsag-reziliencia': typeof FValsagRezilienciaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/aszf': typeof AszfRoute
  '/bcp': typeof BcpRoute
  '/connect': typeof ConnectRoute
  '/devices': typeof DevicesRoute
  '/gdpr': typeof GdprRoute
  '/kotel': typeof KotelRoute
  '/kozosseg': typeof KozossegRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/makro': typeof MakroRoute
  '/oktatas': typeof OktatasRoute
  '/references': typeof ReferencesRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/strategia': typeof StrategiaRoute
  '/ticket': typeof TicketRoute
  '/login_/activate': typeof LoginActivateRoute
  '/f/oktatas-szimulacio/checkout': typeof FOktatasSzimulacioCheckoutRoute
  '/f/oktatas-szimulacio/demo': typeof FOktatasSzimulacioDemoRoute
  '/f/oktatas-szimulacio/pricing': typeof FOktatasSzimulacioPricingRoute
  '/f/uzleti-strategia/checkout': typeof FUzletiStrategiaCheckoutRoute
  '/f/uzleti-strategia/demo': typeof FUzletiStrategiaDemoRoute
  '/f/uzleti-strategia/pricing': typeof FUzletiStrategiaPricingRoute
  '/f/valsag-reziliencia/checkout': typeof FValsagRezilienciaCheckoutRoute
  '/f/valsag-reziliencia/demo': typeof FValsagRezilienciaDemoRoute
  '/f/valsag-reziliencia/pricing': typeof FValsagRezilienciaPricingRoute
  '/f/oktatas-szimulacio/': typeof FOktatasSzimulacioIndexRoute
  '/f/uzleti-strategia/': typeof FUzletiStrategiaIndexRoute
  '/f/valsag-reziliencia/': typeof FValsagRezilienciaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/aszf'
    | '/bcp'
    | '/connect'
    | '/devices'
    | '/gdpr'
    | '/kotel'
    | '/kozosseg'
    | '/login'
    | '/logs'
    | '/makro'
    | '/oktatas'
    | '/references'
    | '/report'
    | '/settings'
    | '/stats'
    | '/strategia'
    | '/ticket'
    | '/login/activate'
    | '/f/oktatas-szimulacio/checkout'
    | '/f/oktatas-szimulacio/demo'
    | '/f/oktatas-szimulacio/pricing'
    | '/f/uzleti-strategia/checkout'
    | '/f/uzleti-strategia/demo'
    | '/f/uzleti-strategia/pricing'
    | '/f/valsag-reziliencia/checkout'
    | '/f/valsag-reziliencia/demo'
    | '/f/valsag-reziliencia/pricing'
    | '/f/oktatas-szimulacio/'
    | '/f/uzleti-strategia/'
    | '/f/valsag-reziliencia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/aszf'
    | '/bcp'
    | '/connect'
    | '/devices'
    | '/gdpr'
    | '/kotel'
    | '/kozosseg'
    | '/login'
    | '/logs'
    | '/makro'
    | '/oktatas'
    | '/references'
    | '/report'
    | '/settings'
    | '/stats'
    | '/strategia'
    | '/ticket'
    | '/login/activate'
    | '/f/oktatas-szimulacio/checkout'
    | '/f/oktatas-szimulacio/demo'
    | '/f/oktatas-szimulacio/pricing'
    | '/f/uzleti-strategia/checkout'
    | '/f/uzleti-strategia/demo'
    | '/f/uzleti-strategia/pricing'
    | '/f/valsag-reziliencia/checkout'
    | '/f/valsag-reziliencia/demo'
    | '/f/valsag-reziliencia/pricing'
    | '/f/oktatas-szimulacio'
    | '/f/uzleti-strategia'
    | '/f/valsag-reziliencia'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/aszf'
    | '/bcp'
    | '/connect'
    | '/devices'
    | '/gdpr'
    | '/kotel'
    | '/kozosseg'
    | '/login'
    | '/logs'
    | '/makro'
    | '/oktatas'
    | '/references'
    | '/report'
    | '/settings'
    | '/stats'
    | '/strategia'
    | '/ticket'
    | '/login_/activate'
    | '/f/oktatas-szimulacio/checkout'
    | '/f/oktatas-szimulacio/demo'
    | '/f/oktatas-szimulacio/pricing'
    | '/f/uzleti-strategia/checkout'
    | '/f/uzleti-strategia/demo'
    | '/f/uzleti-strategia/pricing'
    | '/f/valsag-reziliencia/checkout'
    | '/f/valsag-reziliencia/demo'
    | '/f/valsag-reziliencia/pricing'
    | '/f/oktatas-szimulacio/'
    | '/f/uzleti-strategia/'
    | '/f/valsag-reziliencia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  AszfRoute: typeof AszfRoute
  BcpRoute: typeof BcpRoute
  ConnectRoute: typeof ConnectRoute
  DevicesRoute: typeof DevicesRoute
  GdprRoute: typeof GdprRoute
  KotelRoute: typeof KotelRoute
  KozossegRoute: typeof KozossegRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MakroRoute: typeof MakroRoute
  OktatasRoute: typeof OktatasRoute
  ReferencesRoute: typeof ReferencesRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  StrategiaRoute: typeof StrategiaRoute
  TicketRoute: typeof TicketRoute
  LoginActivateRoute: typeof LoginActivateRoute
  FOktatasSzimulacioCheckoutRoute: typeof FOktatasSzimulacioCheckoutRoute
  FOktatasSzimulacioDemoRoute: typeof FOktatasSzimulacioDemoRoute
  FOktatasSzimulacioPricingRoute: typeof FOktatasSzimulacioPricingRoute
  FUzletiStrategiaCheckoutRoute: typeof FUzletiStrategiaCheckoutRoute
  FUzletiStrategiaDemoRoute: typeof FUzletiStrategiaDemoRoute
  FUzletiStrategiaPricingRoute: typeof FUzletiStrategiaPricingRoute
  FValsagRezilienciaCheckoutRoute: typeof FValsagRezilienciaCheckoutRoute
  FValsagRezilienciaDemoRoute: typeof FValsagRezilienciaDemoRoute
  FValsagRezilienciaPricingRoute: typeof FValsagRezilienciaPricingRoute
  FOktatasSzimulacioIndexRoute: typeof FOktatasSzimulacioIndexRoute
  FUzletiStrategiaIndexRoute: typeof FUzletiStrategiaIndexRoute
  FValsagRezilienciaIndexRoute: typeof FValsagRezilienciaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aszf': {
      id: '/aszf'
      path: '/aszf'
      fullPath: '/aszf'
      preLoaderRoute: typeof AszfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bcp': {
      id: '/bcp'
      path: '/bcp'
      fullPath: '/bcp'
      preLoaderRoute: typeof BcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kotel': {
      id: '/kotel'
      path: '/kotel'
      fullPath: '/kotel'
      preLoaderRoute: typeof KotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kozosseg': {
      id: '/kozosseg'
      path: '/kozosseg'
      fullPath: '/kozosseg'
      preLoaderRoute: typeof KozossegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makro': {
      id: '/makro'
      path: '/makro'
      fullPath: '/makro'
      preLoaderRoute: typeof MakroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oktatas': {
      id: '/oktatas'
      path: '/oktatas'
      fullPath: '/oktatas'
      preLoaderRoute: typeof OktatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategia': {
      id: '/strategia'
      path: '/strategia'
      fullPath: '/strategia'
      preLoaderRoute: typeof StrategiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/activate': {
      id: '/login_/activate'
      path: '/login/activate'
      fullPath: '/login/activate'
      preLoaderRoute: typeof LoginActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/oktatas-szimulacio/': {
      id: '/f/oktatas-szimulacio/'
      path: '/f/oktatas-szimulacio'
      fullPath: '/f/oktatas-szimulacio/'
      preLoaderRoute: typeof FOktatasSzimulacioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/oktatas-szimulacio/checkout': {
      id: '/f/oktatas-szimulacio/checkout'
      path: '/f/oktatas-szimulacio/checkout'
      fullPath: '/f/oktatas-szimulacio/checkout'
      preLoaderRoute: typeof FOktatasSzimulacioCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/oktatas-szimulacio/demo': {
      id: '/f/oktatas-szimulacio/demo'
      path: '/f/oktatas-szimulacio/demo'
      fullPath: '/f/oktatas-szimulacio/demo'
      preLoaderRoute: typeof FOktatasSzimulacioDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/oktatas-szimulacio/pricing': {
      id: '/f/oktatas-szimulacio/pricing'
      path: '/f/oktatas-szimulacio/pricing'
      fullPath: '/f/oktatas-szimulacio/pricing'
      preLoaderRoute: typeof FOktatasSzimulacioPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/uzleti-strategia/': {
      id: '/f/uzleti-strategia/'
      path: '/f/uzleti-strategia'
      fullPath: '/f/uzleti-strategia/'
      preLoaderRoute: typeof FUzletiStrategiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/uzleti-strategia/checkout': {
      id: '/f/uzleti-strategia/checkout'
      path: '/f/uzleti-strategia/checkout'
      fullPath: '/f/uzleti-strategia/checkout'
      preLoaderRoute: typeof FUzletiStrategiaCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/uzleti-strategia/demo': {
      id: '/f/uzleti-strategia/demo'
      path: '/f/uzleti-strategia/demo'
      fullPath: '/f/uzleti-strategia/demo'
      preLoaderRoute: typeof FUzletiStrategiaDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/uzleti-strategia/pricing': {
      id: '/f/uzleti-strategia/pricing'
      path: '/f/uzleti-strategia/pricing'
      fullPath: '/f/uzleti-strategia/pricing'
      preLoaderRoute: typeof FUzletiStrategiaPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/valsag-reziliencia/': {
      id: '/f/valsag-reziliencia/'
      path: '/f/valsag-reziliencia'
      fullPath: '/f/valsag-reziliencia/'
      preLoaderRoute: typeof FValsagRezilienciaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/valsag-reziliencia/checkout': {
      id: '/f/valsag-reziliencia/checkout'
      path: '/f/valsag-reziliencia/checkout'
      fullPath: '/f/valsag-reziliencia/checkout'
      preLoaderRoute: typeof FValsagRezilienciaCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/valsag-reziliencia/demo': {
      id: '/f/valsag-reziliencia/demo'
      path: '/f/valsag-reziliencia/demo'
      fullPath: '/f/valsag-reziliencia/demo'
      preLoaderRoute: typeof FValsagRezilienciaDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/valsag-reziliencia/pricing': {
      id: '/f/valsag-reziliencia/pricing'
      path: '/f/valsag-reziliencia/pricing'
      fullPath: '/f/valsag-reziliencia/pricing'
      preLoaderRoute: typeof FValsagRezilienciaPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  AszfRoute: AszfRoute,
  BcpRoute: BcpRoute,
  ConnectRoute: ConnectRoute,
  DevicesRoute: DevicesRoute,
  GdprRoute: GdprRoute,
  KotelRoute: KotelRoute,
  KozossegRoute: KozossegRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MakroRoute: MakroRoute,
  OktatasRoute: OktatasRoute,
  ReferencesRoute: ReferencesRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  StrategiaRoute: StrategiaRoute,
  TicketRoute: TicketRoute,
  LoginActivateRoute: LoginActivateRoute,
  FOktatasSzimulacioCheckoutRoute: FOktatasSzimulacioCheckoutRoute,
  FOktatasSzimulacioDemoRoute: FOktatasSzimulacioDemoRoute,
  FOktatasSzimulacioPricingRoute: FOktatasSzimulacioPricingRoute,
  FUzletiStrategiaCheckoutRoute: FUzletiStrategiaCheckoutRoute,
  FUzletiStrategiaDemoRoute: FUzletiStrategiaDemoRoute,
  FUzletiStrategiaPricingRoute: FUzletiStrategiaPricingRoute,
  FValsagRezilienciaCheckoutRoute: FValsagRezilienciaCheckoutRoute,
  FValsagRezilienciaDemoRoute: FValsagRezilienciaDemoRoute,
  FValsagRezilienciaPricingRoute: FValsagRezilienciaPricingRoute,
  FOktatasSzimulacioIndexRoute: FOktatasSzimulacioIndexRoute,
  FUzletiStrategiaIndexRoute: FUzletiStrategiaIndexRoute,
  FValsagRezilienciaIndexRoute: FValsagRezilienciaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
