/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as FMinosegKoltsegIndexRouteImport } from './routes/f/minoseg-koltseg/index'
import { Route as FMinosegKoltsegCheckoutRouteImport } from './routes/f/minoseg-koltseg/checkout'
import { Route as FMinosegKoltsegDemoRouteImport } from './routes/f/minoseg-koltseg/demo'
import { Route as FMinosegKoltsegPricingRouteImport } from './routes/f/minoseg-koltseg/pricing'
import { Route as FMultiSiteIndexRouteImport } from './routes/f/multi-site/index'
import { Route as FMultiSiteCheckoutRouteImport } from './routes/f/multi-site/checkout'
import { Route as FMultiSiteDemoRouteImport } from './routes/f/multi-site/demo'
import { Route as FMultiSitePricingRouteImport } from './routes/f/multi-site/pricing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const FMinosegKoltsegIndexRoute = FMinosegKoltsegIndexRouteImport.update({
  id: '/f/minoseg-koltseg/',
  path: '/f/minoseg-koltseg/',
  getParentRoute: () => rootRouteImport,
} as any)
const FMinosegKoltsegCheckoutRoute = FMinosegKoltsegCheckoutRouteImport.update({
  id: '/f/minoseg-koltseg/checkout',
  path: '/f/minoseg-koltseg/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FMinosegKoltsegDemoRoute = FMinosegKoltsegDemoRouteImport.update({
  id: '/f/minoseg-koltseg/demo',
  path: '/f/minoseg-koltseg/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FMinosegKoltsegPricingRoute = FMinosegKoltsegPricingRouteImport.update({
  id: '/f/minoseg-koltseg/pricing',
  path: '/f/minoseg-koltseg/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FMultiSiteIndexRoute = FMultiSiteIndexRouteImport.update({
  id: '/f/multi-site/',
  path: '/f/multi-site/',
  getParentRoute: () => rootRouteImport,
} as any)
const FMultiSiteCheckoutRoute = FMultiSiteCheckoutRouteImport.update({
  id: '/f/multi-site/checkout',
  path: '/f/multi-site/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FMultiSiteDemoRoute = FMultiSiteDemoRouteImport.update({
  id: '/f/multi-site/demo',
  path: '/f/multi-site/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FMultiSitePricingRoute = FMultiSitePricingRouteImport.update({
  id: '/f/multi-site/pricing',
  path: '/f/multi-site/pricing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/references': typeof ReferencesRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/f/minoseg-koltseg/checkout': typeof FMinosegKoltsegCheckoutRoute
  '/f/minoseg-koltseg/demo': typeof FMinosegKoltsegDemoRoute
  '/f/minoseg-koltseg/pricing': typeof FMinosegKoltsegPricingRoute
  '/f/multi-site/checkout': typeof FMultiSiteCheckoutRoute
  '/f/multi-site/demo': typeof FMultiSiteDemoRoute
  '/f/multi-site/pricing': typeof FMultiSitePricingRoute
  '/f/minoseg-koltseg/': typeof FMinosegKoltsegIndexRoute
  '/f/multi-site/': typeof FMultiSiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/references': typeof ReferencesRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/f/minoseg-koltseg/checkout': typeof FMinosegKoltsegCheckoutRoute
  '/f/minoseg-koltseg/demo': typeof FMinosegKoltsegDemoRoute
  '/f/minoseg-koltseg/pricing': typeof FMinosegKoltsegPricingRoute
  '/f/multi-site/checkout': typeof FMultiSiteCheckoutRoute
  '/f/multi-site/demo': typeof FMultiSiteDemoRoute
  '/f/multi-site/pricing': typeof FMultiSitePricingRoute
  '/f/minoseg-koltseg': typeof FMinosegKoltsegIndexRoute
  '/f/multi-site': typeof FMultiSiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/references': typeof ReferencesRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/f/minoseg-koltseg/checkout': typeof FMinosegKoltsegCheckoutRoute
  '/f/minoseg-koltseg/demo': typeof FMinosegKoltsegDemoRoute
  '/f/minoseg-koltseg/pricing': typeof FMinosegKoltsegPricingRoute
  '/f/multi-site/checkout': typeof FMultiSiteCheckoutRoute
  '/f/multi-site/demo': typeof FMultiSiteDemoRoute
  '/f/multi-site/pricing': typeof FMultiSitePricingRoute
  '/f/minoseg-koltseg/': typeof FMinosegKoltsegIndexRoute
  '/f/multi-site/': typeof FMultiSiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/devices'
    | '/login'
    | '/logs'
    | '/references'
    | '/report'
    | '/settings'
    | '/stats'
    | '/f/minoseg-koltseg/checkout'
    | '/f/minoseg-koltseg/demo'
    | '/f/minoseg-koltseg/pricing'
    | '/f/multi-site/checkout'
    | '/f/multi-site/demo'
    | '/f/multi-site/pricing'
    | '/f/minoseg-koltseg/'
    | '/f/multi-site/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/devices'
    | '/login'
    | '/logs'
    | '/references'
    | '/report'
    | '/settings'
    | '/stats'
    | '/f/minoseg-koltseg/checkout'
    | '/f/minoseg-koltseg/demo'
    | '/f/minoseg-koltseg/pricing'
    | '/f/multi-site/checkout'
    | '/f/multi-site/demo'
    | '/f/multi-site/pricing'
    | '/f/minoseg-koltseg'
    | '/f/multi-site'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/devices'
    | '/login'
    | '/logs'
    | '/references'
    | '/report'
    | '/settings'
    | '/stats'
    | '/f/minoseg-koltseg/checkout'
    | '/f/minoseg-koltseg/demo'
    | '/f/minoseg-koltseg/pricing'
    | '/f/multi-site/checkout'
    | '/f/multi-site/demo'
    | '/f/multi-site/pricing'
    | '/f/minoseg-koltseg/'
    | '/f/multi-site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  DevicesRoute: typeof DevicesRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ReferencesRoute: typeof ReferencesRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  FMinosegKoltsegCheckoutRoute: typeof FMinosegKoltsegCheckoutRoute
  FMinosegKoltsegDemoRoute: typeof FMinosegKoltsegDemoRoute
  FMinosegKoltsegPricingRoute: typeof FMinosegKoltsegPricingRoute
  FMultiSiteCheckoutRoute: typeof FMultiSiteCheckoutRoute
  FMultiSiteDemoRoute: typeof FMultiSiteDemoRoute
  FMultiSitePricingRoute: typeof FMultiSitePricingRoute
  FMinosegKoltsegIndexRoute: typeof FMinosegKoltsegIndexRoute
  FMultiSiteIndexRoute: typeof FMultiSiteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/minoseg-koltseg/': {
      id: '/f/minoseg-koltseg/'
      path: '/f/minoseg-koltseg'
      fullPath: '/f/minoseg-koltseg/'
      preLoaderRoute: typeof FMinosegKoltsegIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/minoseg-koltseg/checkout': {
      id: '/f/minoseg-koltseg/checkout'
      path: '/f/minoseg-koltseg/checkout'
      fullPath: '/f/minoseg-koltseg/checkout'
      preLoaderRoute: typeof FMinosegKoltsegCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/minoseg-koltseg/demo': {
      id: '/f/minoseg-koltseg/demo'
      path: '/f/minoseg-koltseg/demo'
      fullPath: '/f/minoseg-koltseg/demo'
      preLoaderRoute: typeof FMinosegKoltsegDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/minoseg-koltseg/pricing': {
      id: '/f/minoseg-koltseg/pricing'
      path: '/f/minoseg-koltseg/pricing'
      fullPath: '/f/minoseg-koltseg/pricing'
      preLoaderRoute: typeof FMinosegKoltsegPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/multi-site/': {
      id: '/f/multi-site/'
      path: '/f/multi-site'
      fullPath: '/f/multi-site/'
      preLoaderRoute: typeof FMultiSiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/multi-site/checkout': {
      id: '/f/multi-site/checkout'
      path: '/f/multi-site/checkout'
      fullPath: '/f/multi-site/checkout'
      preLoaderRoute: typeof FMultiSiteCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/multi-site/demo': {
      id: '/f/multi-site/demo'
      path: '/f/multi-site/demo'
      fullPath: '/f/multi-site/demo'
      preLoaderRoute: typeof FMultiSiteDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/multi-site/pricing': {
      id: '/f/multi-site/pricing'
      path: '/f/multi-site/pricing'
      fullPath: '/f/multi-site/pricing'
      preLoaderRoute: typeof FMultiSitePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  DevicesRoute: DevicesRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ReferencesRoute: ReferencesRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  FMinosegKoltsegCheckoutRoute: FMinosegKoltsegCheckoutRoute,
  FMinosegKoltsegDemoRoute: FMinosegKoltsegDemoRoute,
  FMinosegKoltsegPricingRoute: FMinosegKoltsegPricingRoute,
  FMultiSiteCheckoutRoute: FMultiSiteCheckoutRoute,
  FMultiSiteDemoRoute: FMultiSiteDemoRoute,
  FMultiSitePricingRoute: FMultiSitePricingRoute,
  FMinosegKoltsegIndexRoute: FMinosegKoltsegIndexRoute,
  FMultiSiteIndexRoute: FMultiSiteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
